blogicum/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:id>/', views.post_detail, name='post_detail'),
    path('category/<slug:category_slug>/',
         views.category_posts, name='category_posts'),
]

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('pages/', include('pages.urls', namespace='pages')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogicum/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('rules/', views.rules, name='rules'),
]

blogicum/blog/models.py
# from django.db import models

# Create your models here.

blogicum/blog/views.py
from django.shortcuts import render

posts = [
    {
        'id': 0,
        'location': 'Остров отчаянья',
        'date': '30 сентября 1659 года',
        'category': 'travel',
        'text': '''Наш корабль, застигнутый в открытом море
                страшным штормом, потерпел крушение.
                Весь экипаж, кроме меня, утонул; я же,
                несчастный Робинзон Крузо, был выброшен
                полумёртвым на берег этого проклятого острова,
                который назвал островом Отчаяния.''',
    },
    {
        'id': 1,
        'location': 'Остров отчаянья',
        'date': '1 октября 1659 года',
        'category': 'not-my-day',
        'text': '''Проснувшись поутру, я увидел, что наш корабль сняло
                с мели приливом и пригнало гораздо ближе к берегу.
                Это подало мне надежду, что, когда ветер стихнет,
                мне удастся добраться до корабля и запастись едой и
                другими необходимыми вещами. Я немного приободрился,
                хотя печаль о погибших товарищах не покидала меня.
                Мне всё думалось, что, останься мы на корабле, мы
                непременно спаслись бы. Теперь из его обломков мы могли бы
                построить баркас, на котором и выбрались бы из этого
                гиблого места.''',
    },
    {
        'id': 2,
        'location': 'Остров отчаянья',
        'date': '25 октября 1659 года',
        'category': 'not-my-day',
        'text': '''Всю ночь и весь день шёл дождь и дул сильный
                порывистый ветер. 25 октября.  Корабль за ночь разбило
                в щепки; на том месте, где он стоял, торчат какие-то
                жалкие обломки,  да и те видны только во время отлива.
                Весь этот день я хлопотал  около вещей: укрывал и
                укутывал их, чтобы не испортились от дождя.''',
    },
]


def index(request):
    context = {'posts': posts}  # Передаем posts в контекст
    return render(request, 'blog/index.html', context)


def post_detail(request, id):
    post = posts[id]  # Для временных данных
    context = {'post': post}
    return render(request, 'blog/detail.html', context)


def category_posts(request, category_slug):
    context = {'category': category_slug}
    return render(request, 'blog/category.html', context)

blogicum/pages/views.py
from django.shortcuts import render


def about(request):
    return render(request, 'pages/about.html')


def rules(request):
    return render(request, 'pages/rules.html')

blogicum/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'includes/header.html' %}
    
    <main class="container py-5">
        {% block content %}
        {% endblock %}
    </main>
    
    {% include 'includes/footer.html' %}
    
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blogicum/templates/blog/category.html
{% extends "base.html" %}
{% load static %}

{% block title %}Публикации в категории {{ category }}{% endblock %}

{% block content %}
<main>
  <div class="container py-5">
    <h1>Публикации в категории {{ category }}</h1>
    
    {% for post in posts %}
      <article class="mb-5">
        <h2>{{ post.location }}</h2>
        <p class="text-muted">{{ post.date }}</p>
        <p>{{ post.text|truncatewords:10 }}</p>
        <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">
          Читать полный текст
        </a>
      </article>
    {% empty %}
      <p>В этой категории пока нет публикаций</p>
    {% endfor %}
  </div>
</main>
{% endblock %}

blogicum/templates/blog/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ post.location }}. {{ post.date }}{% endblock %}

{% block content %}
<main>
  <div class="container py-5">
    <article>
      <ul>
        <li>
          Место: {{ post.location }}              
        </li>
        <li>
          Дата: {{ post.date }}
        </li>
        <li>
          Категория: <a href="{% url 'blog:category_posts' post.category %}">{{ post.category }}</a>
        </li>
      </ul>         
      <p>{{ post.text|linebreaksbr }}</p>          
    </article>                
  </div>
</main>
{% endblock %}

blogicum/templates/blog/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Лента записей{% endblock %}

{% block content %}
<main>
  <div class="container py-5">
    <h1 class="pb-2 mb-0">Лента записей</h1>
    
    {% for post in posts reversed %}
    <article class="border rounded p-3 mb-4">
      <ul class="list-unstyled mb-0">
        <li>
          Место: {{ post.location }}              
        </li>
        <li>
          Дата: {{ post.date }}
        </li>
        <li>
          Категория: <a href="{% url 'blog:category_posts' post.category %}">{{ post.category }}</a>
        </li>
      </ul>
      <p class="mt-3">{{ post.text|truncatewords:10 }}</p>
      <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">
        Читать полный текст
      </a>
    </article>
    {% endfor %}
  </div>
</main>
{% endblock %}

blogicum/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Блогикум</p>    
</footer>

blogicum/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Блогикум
      </a>        
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'index' %}active{% endif %}" 
             href="{% url 'blog:index' %}">
            Лента записей
          </a>
        </li>
        <li class="nav-item">              
          <a class="nav-link {% if request.resolver_match.url_name == 'about' %}active{% endif %}" 
             href="{% url 'pages:about' %}">
            О проекте
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'rules' %}active{% endif %}" 
             href="{% url 'pages:rules' %}">
            Наши правила
          </a>
        </li>
      </ul>      
    </div>
  </nav> 
</header>

blogicum/templates/pages/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}О проекте{% endblock %}

{% block content %}
<main>
  <div class="container py-5">                        
    <h1>О проекте</h1>
    <p>
      Блогикум — это дом для творческих людей. Это — сообщество людей, для которых 
      нет грани между ведением блога и дружбой в социальных сетях. 
    </p>
    <p>
      Дружба и рассказы о новых, неизведанных впечатлениях — вот 
      что вы найдете на нашем ресурсе. Миллионы блогов по различным темам. 
      Путешествия, политики, развлечения, мода, литература, дизайн и все 
      другие сферы человеческой деятельности. 
    </p>
    <p>
      Творчество, разнообразие и свобода взглядов и самовыражения — 
      основные черты наших пользователей.
    </p>           
  </div>
</main>
{% endblock %}

blogicum/templates/pages/rules.html
{% extends "base.html" %}
{% load static %}

{% block title %}Наши правила{% endblock %}

{% block content %}
<main>
  <div class="container py-5">                        
    <h1>Наши правила</h1>
    <p>
      <b>Cамовыражение.</b> У наших пользователей должна 
      быть возможность создать что-то своё, выразить себя, 
      свои мысли и чувства.
    </p>
    <p>
      <b>Многообразие.</b> Мы уважаем и приветствуем разные 
      мнения и культуры. Блогикум — это место, объединяющее 
      самых разных людей. Поделитесь своим уникальным взглядом на мир.  
    </p>
    <p>
      <b>Творчество.</b> Не важно, в какой области вы творите, 
      это может быть литература, дизайн, программирование. 
      Наши инструменты помогут вам раскрыть талант максимально 
      просто и комфортно.   
    </p>
    <p>
      <b>Личность.</b> Мы сохраним ваши сокровенные мысли в тайне. 
      Делитесь своей информацией только с теми, кого выбрали. 
      Как и насколько засекречивать вашу личную информацию — 
      определяете вы и только вы.  
    </p>
  </div>
</main>
{% endblock %}